"""
内容生成任务执行器

负责执行内容生成任务，调用 content-creator CLI 生成内容并保存到数据库
"""
import time
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session

from app.services.scheduler_service import TaskExecutor, TaskExecutionResult
from app.services.content_creator_service import content_creator_service
from app.models.content import Content
from app.utils.custom_logger import log


class ContentGenerationExecutor(TaskExecutor):
    """
    内容生成任务执行器

    功能：
    1. 从任务配置中读取参数（账号ID、选题等）
    2. 调用 content-creator CLI 生成内容
    3. 将生成的内容保存到数据库
    4. 更新任务执行记录
    """

    @property
    def executor_type(self) -> str:
        """返回执行器类型标识"""
        return "content_generation"

    def validate_params(self, task_params: Dict[str, Any]) -> bool:
        """
        验证任务参数

        Args:
            task_params: 任务参数字典

        Returns:
            bool: 参数是否有效

        必需参数:
            - account_id: 账号ID（必需）

        可选参数:
            - topic: 选题（如果没有提供，需要从其他来源获取）
            - title: 标题（可选，content-creator 会自动生成）
            - requirements: 创作要求（可选）
            - target_audience: 目标受众（可选，默认：普通读者）
            - tone: 语气风格（可选，默认：友好专业）
        """
        # 检查必需的参数
        if "account_id" not in task_params:
            log.error("Missing required parameter: account_id")
            return False

        account_id = task_params.get("account_id")
        if not isinstance(account_id, int) or account_id <= 0:
            log.error(f"Invalid account_id: {account_id}")
            return False

        # 检查选题（可选，但通常需要）
        topic = task_params.get("topic")
        if not topic:
            log.warning("No topic provided in task params")
            # 注意：选题可能从其他来源获取，所以这里只是警告

        log.info(f"Task params validation passed: account_id={account_id}, topic={topic}")
        return True

    async def execute(
        self,
        task_id: int,
        task_params: Dict[str, Any],
        db: Session
    ) -> TaskExecutionResult:
        """
        执行内容生成任务

        Args:
            task_id: 任务ID
            task_params: 任务参数字典
            db: 数据库会话

        Returns:
            TaskExecutionResult: 任务执行结果

        执行流程:
            1. 提取任务参数
            2. 调用 content-creator CLI 生成内容
            3. 保存生成的内容到数据库
            4. 返回执行结果
        """
        start_time = time.time()
        log.info(f"Executing content generation task {task_id}")

        try:
            # 1. 提取任务参数
            account_id = task_params.get("account_id")
            topic = task_params.get("topic")
            title = task_params.get("title")
            requirements = task_params.get("requirements")
            target_audience = task_params.get("target_audience", "普通读者")
            tone = task_params.get("tone", "友好专业")

            log.info(f"Task params: account_id={account_id}, topic={topic}, tone={tone}")

            # 2. 调用 content-creator CLI 生成内容
            log.info(f"Calling content-creator CLI for topic: {topic}")

            try:
                creator_result = content_creator_service.create_content(
                    topic=topic,
                    requirements=requirements,
                    target_audience=target_audience,
                    tone=tone,
                    account_id=account_id,
                    db=db
                )

                log.info(f"Content-creator CLI completed successfully")
                log.debug(f"Creator result keys: {creator_result.keys()}")

            except Exception as e:
                error_msg = f"Failed to call content-creator CLI: {str(e)}"
                log.error(error_msg)
                duration = time.time() - start_time
                return TaskExecutionResult.failure_result(
                    message=error_msg,
                    error=str(e),
                    duration=duration
                )

            # 3. 保存生成的内容到数据库
            try:
                # 提取生成的内容
                generated_content = creator_result.get("content", "")
                if not generated_content:
                    error_msg = "No content generated by content-creator CLI"
                    log.error(error_msg)
                    duration = time.time() - start_time
                    return TaskExecutionResult.failure_result(
                        message=error_msg,
                        error="EmptyContent",
                        duration=duration
                    )

                # 提取图片列表
                images = creator_result.get("images", [])

                # 生成标题（如果没有提供）
                if not title:
                    # 从内容中提取第一行作为标题（如果是 Markdown）
                    lines = generated_content.strip().split("\n")
                    for line in lines:
                        line = line.strip()
                        if line.startswith("# "):
                            title = line[2:].strip()
                            break
                    if not title:
                        # 使用选题作为标题
                        title = topic if topic else f"Untitled Content (Task {task_id})"

                # 计算字数
                word_count = len(generated_content)

                # 创建 Content 记录
                content_record = Content(
                    account_id=account_id,
                    title=title,
                    content=generated_content,
                    summary=creator_result.get("summary"),  # 如果有的话
                    topic=topic,
                    word_count=word_count,
                    images=images,
                    # 默认状态
                    review_status="pending",
                    publish_status="draft"
                )

                db.add(content_record)
                db.commit()
                db.refresh(content_record)

                log.info(f"Content saved to database: id={content_record.id}, title={title}")

                # 4. 返回执行结果
                duration = time.time() - start_time
                return TaskExecutionResult.success_result(
                    message=f"Successfully generated and saved content: {title}",
                    data={
                        "content_id": content_record.id,
                        "title": title,
                        "word_count": word_count,
                        "images_count": len(images),
                        "creator_task_id": creator_result.get("task_id"),
                        "quality_score": creator_result.get("quality_score"),
                        "quality_passed": creator_result.get("quality_passed")
                    },
                    duration=duration,
                    metadata={
                        "account_id": account_id,
                        "topic": topic,
                        "creator_duration": creator_result.get("duration")
                    }
                )

            except Exception as e:
                error_msg = f"Failed to save content to database: {str(e)}"
                log.error(error_msg)
                log.exception("Database save error")
                duration = time.time() - start_time
                return TaskExecutionResult.failure_result(
                    message=error_msg,
                    error=str(e),
                    duration=duration,
                    metadata={
                        "creator_result": creator_result
                    }
                )

        except Exception as e:
            # 捕获所有未处理的异常
            error_msg = f"Unexpected error during content generation: {str(e)}"
            log.error(error_msg)
            log.exception("Content generation execution error")
            duration = time.time() - start_time
            return TaskExecutionResult.failure_result(
                message=error_msg,
                error=str(e),
                duration=duration
            )
